<?php

namespace Database\Seeders;

use App\Models\Reference\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            // ─────────────── East Africa (core market) ───────────────
            [
                'iso2' => 'UG', 'iso3' => 'UGA', 'name' => 'Uganda',
                'official_name' => 'Republic of Uganda',
                'phone_code' => '256', 'default_currency' => 'UGX',
                'region' => 'Africa', 'subregion' => 'Eastern Africa',
                'flag_emoji' => '🇺🇬',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'bank_transfer', 'card'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id'],
            ],
            [
                'iso2' => 'KE', 'iso3' => 'KEN', 'name' => 'Kenya',
                'official_name' => 'Republic of Kenya',
                'phone_code' => '254', 'default_currency' => 'KES',
                'region' => 'Africa', 'subregion' => 'Eastern Africa',
                'flag_emoji' => '🇰🇪',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'bank_transfer', 'card'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id'],
            ],
            [
                'iso2' => 'TZ', 'iso3' => 'TZA', 'name' => 'Tanzania',
                'official_name' => 'United Republic of Tanzania',
                'phone_code' => '255', 'default_currency' => 'TZS',
                'region' => 'Africa', 'subregion' => 'Eastern Africa',
                'flag_emoji' => '🇹🇿',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => false,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'bank_transfer'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id'],
            ],
            [
                'iso2' => 'RW', 'iso3' => 'RWA', 'name' => 'Rwanda',
                'official_name' => 'Republic of Rwanda',
                'phone_code' => '250', 'default_currency' => 'RWF',
                'region' => 'Africa', 'subregion' => 'Eastern Africa',
                'flag_emoji' => '🇷🇼',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => false,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'bank_transfer'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id'],
            ],
            [
                'iso2' => 'BI', 'iso3' => 'BDI', 'name' => 'Burundi',
                'official_name' => 'Republic of Burundi',
                'phone_code' => '257', 'default_currency' => 'BIF',
                'region' => 'Africa', 'subregion' => 'Eastern Africa',
                'flag_emoji' => '🇧🇮',
                'is_supported' => false, 'collections_enabled' => false, 'payouts_enabled' => false,
                'is_high_risk' => true, 'is_sanctioned' => false,
            ],
            [
                'iso2' => 'SS', 'iso3' => 'SSD', 'name' => 'South Sudan',
                'official_name' => 'Republic of South Sudan',
                'phone_code' => '211', 'default_currency' => 'SSP',
                'region' => 'Africa', 'subregion' => 'Eastern Africa',
                'flag_emoji' => '🇸🇸',
                'is_supported' => false, 'collections_enabled' => false, 'payouts_enabled' => false,
                'is_high_risk' => true, 'is_sanctioned' => false,
            ],
            [
                'iso2' => 'ET', 'iso3' => 'ETH', 'name' => 'Ethiopia',
                'official_name' => 'Federal Democratic Republic of Ethiopia',
                'phone_code' => '251', 'default_currency' => 'ETB',
                'region' => 'Africa', 'subregion' => 'Eastern Africa',
                'flag_emoji' => '🇪🇹',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => false,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'bank_transfer'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id'],
            ],

            // ─────────────── West Africa ───────────────
            [
                'iso2' => 'NG', 'iso3' => 'NGA', 'name' => 'Nigeria',
                'official_name' => 'Federal Republic of Nigeria',
                'phone_code' => '234', 'default_currency' => 'NGN',
                'region' => 'Africa', 'subregion' => 'Western Africa',
                'flag_emoji' => '🇳🇬',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'mobile_money'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id', 'proof_of_address'],
            ],
            [
                'iso2' => 'GH', 'iso3' => 'GHA', 'name' => 'Ghana',
                'official_name' => 'Republic of Ghana',
                'phone_code' => '233', 'default_currency' => 'GHS',
                'region' => 'Africa', 'subregion' => 'Western Africa',
                'flag_emoji' => '🇬🇭',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'mobile_money', 'bank_transfer'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id'],
            ],
            [
                'iso2' => 'CI', 'iso3' => 'CIV', 'name' => "Côte d'Ivoire",
                'official_name' => "Republic of Côte d'Ivoire",
                'phone_code' => '225', 'default_currency' => 'XOF',
                'region' => 'Africa', 'subregion' => 'Western Africa',
                'flag_emoji' => '🇨🇮',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => false,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'bank_transfer', 'card'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id'],
            ],
            [
                'iso2' => 'SN', 'iso3' => 'SEN', 'name' => 'Senegal',
                'official_name' => 'Republic of Senegal',
                'phone_code' => '221', 'default_currency' => 'XOF',
                'region' => 'Africa', 'subregion' => 'Western Africa',
                'flag_emoji' => '🇸🇳',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => false,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'card'],
            ],

            // ─────────────── Southern Africa ───────────────
            [
                'iso2' => 'ZA', 'iso3' => 'ZAF', 'name' => 'South Africa',
                'official_name' => 'Republic of South Africa',
                'phone_code' => '27', 'default_currency' => 'ZAR',
                'region' => 'Africa', 'subregion' => 'Southern Africa',
                'flag_emoji' => '🇿🇦',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'eft'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id', 'proof_of_address'],
            ],
            [
                'iso2' => 'ZM', 'iso3' => 'ZMB', 'name' => 'Zambia',
                'official_name' => 'Republic of Zambia',
                'phone_code' => '260', 'default_currency' => 'ZMW',
                'region' => 'Africa', 'subregion' => 'Southern Africa',
                'flag_emoji' => '🇿🇲',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => false,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['mobile_money', 'bank_transfer'],
            ],

            // ─────────────── North Africa ───────────────
            [
                'iso2' => 'EG', 'iso3' => 'EGY', 'name' => 'Egypt',
                'official_name' => 'Arab Republic of Egypt',
                'phone_code' => '20', 'default_currency' => 'EGP',
                'region' => 'Africa', 'subregion' => 'Northern Africa',
                'flag_emoji' => '🇪🇬',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'mobile_money'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id'],
            ],
            [
                'iso2' => 'MA', 'iso3' => 'MAR', 'name' => 'Morocco',
                'official_name' => 'Kingdom of Morocco',
                'phone_code' => '212', 'default_currency' => 'MAD',
                'region' => 'Africa', 'subregion' => 'Northern Africa',
                'flag_emoji' => '🇲🇦',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => false,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer'],
            ],

            // ─────────────── Europe ───────────────
            [
                'iso2' => 'GB', 'iso3' => 'GBR', 'name' => 'United Kingdom',
                'official_name' => 'United Kingdom of Great Britain and Northern Ireland',
                'phone_code' => '44', 'default_currency' => 'GBP',
                'region' => 'Europe', 'subregion' => 'Northern Europe',
                'flag_emoji' => '🇬🇧',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'sepa', 'faster_payments'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id', 'proof_of_address', 'bank_statement'],
            ],
            [
                'iso2' => 'DE', 'iso3' => 'DEU', 'name' => 'Germany',
                'official_name' => 'Federal Republic of Germany',
                'phone_code' => '49', 'default_currency' => 'EUR',
                'region' => 'Europe', 'subregion' => 'Western Europe',
                'flag_emoji' => '🇩🇪',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'sepa'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id', 'proof_of_address'],
            ],
            [
                'iso2' => 'FR', 'iso3' => 'FRA', 'name' => 'France',
                'official_name' => 'French Republic',
                'phone_code' => '33', 'default_currency' => 'EUR',
                'region' => 'Europe', 'subregion' => 'Western Europe',
                'flag_emoji' => '🇫🇷',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'sepa'],
            ],
            [
                'iso2' => 'NL', 'iso3' => 'NLD', 'name' => 'Netherlands',
                'official_name' => 'Kingdom of the Netherlands',
                'phone_code' => '31', 'default_currency' => 'EUR',
                'region' => 'Europe', 'subregion' => 'Western Europe',
                'flag_emoji' => '🇳🇱',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'sepa', 'ideal'],
            ],
            [
                'iso2' => 'CH', 'iso3' => 'CHE', 'name' => 'Switzerland',
                'official_name' => 'Swiss Confederation',
                'phone_code' => '41', 'default_currency' => 'CHF',
                'region' => 'Europe', 'subregion' => 'Western Europe',
                'flag_emoji' => '🇨🇭',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'sepa'],
            ],

            // ─────────────── Americas ───────────────
            [
                'iso2' => 'US', 'iso3' => 'USA', 'name' => 'United States',
                'official_name' => 'United States of America',
                'phone_code' => '1', 'default_currency' => 'USD',
                'region' => 'Americas', 'subregion' => 'Northern America',
                'flag_emoji' => '🇺🇸',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'ach', 'wire', 'bank_transfer'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id', 'proof_of_address', 'bank_statement'],
            ],
            [
                'iso2' => 'CA', 'iso3' => 'CAN', 'name' => 'Canada',
                'official_name' => 'Canada',
                'phone_code' => '1', 'default_currency' => 'CAD',
                'region' => 'Americas', 'subregion' => 'Northern America',
                'flag_emoji' => '🇨🇦',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'interac'],
            ],
            [
                'iso2' => 'BR', 'iso3' => 'BRA', 'name' => 'Brazil',
                'official_name' => 'Federative Republic of Brazil',
                'phone_code' => '55', 'default_currency' => 'BRL',
                'region' => 'Americas', 'subregion' => 'South America',
                'flag_emoji' => '🇧🇷',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'pix', 'bank_transfer', 'boleto'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id'],
            ],
            [
                'iso2' => 'MX', 'iso3' => 'MEX', 'name' => 'Mexico',
                'official_name' => 'United Mexican States',
                'phone_code' => '52', 'default_currency' => 'MXN',
                'region' => 'Americas', 'subregion' => 'Central America',
                'flag_emoji' => '🇲🇽',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'spei'],
            ],

            // ─────────────── Middle East ───────────────
            [
                'iso2' => 'AE', 'iso3' => 'ARE', 'name' => 'United Arab Emirates',
                'official_name' => 'United Arab Emirates',
                'phone_code' => '971', 'default_currency' => 'AED',
                'region' => 'Asia', 'subregion' => 'Western Asia',
                'flag_emoji' => '🇦🇪',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id', 'proof_of_address'],
            ],
            [
                'iso2' => 'SA', 'iso3' => 'SAU', 'name' => 'Saudi Arabia',
                'official_name' => 'Kingdom of Saudi Arabia',
                'phone_code' => '966', 'default_currency' => 'SAR',
                'region' => 'Asia', 'subregion' => 'Western Asia',
                'flag_emoji' => '🇸🇦',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'mada'],
            ],

            // ─────────────── Asia ───────────────
            [
                'iso2' => 'IN', 'iso3' => 'IND', 'name' => 'India',
                'official_name' => 'Republic of India',
                'phone_code' => '91', 'default_currency' => 'INR',
                'region' => 'Asia', 'subregion' => 'Southern Asia',
                'flag_emoji' => '🇮🇳',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'upi', 'netbanking', 'bank_transfer'],
                'required_business_documents' => ['certificate_of_incorporation', 'tax_id', 'directors_id', 'proof_of_address'],
            ],
            [
                'iso2' => 'SG', 'iso3' => 'SGP', 'name' => 'Singapore',
                'official_name' => 'Republic of Singapore',
                'phone_code' => '65', 'default_currency' => 'SGD',
                'region' => 'Asia', 'subregion' => 'South-Eastern Asia',
                'flag_emoji' => '🇸🇬',
                'is_supported' => true, 'collections_enabled' => true, 'payouts_enabled' => true,
                'is_high_risk' => false, 'is_sanctioned' => false,
                'supported_payment_methods' => ['card', 'bank_transfer', 'paynow'],
            ],

            // ─────────────── Sanctioned / restricted ───────────────
            [
                'iso2' => 'IR', 'iso3' => 'IRN', 'name' => 'Iran',
                'official_name' => 'Islamic Republic of Iran',
                'phone_code' => '98', 'default_currency' => 'IRR',
                'region' => 'Asia', 'subregion' => 'Southern Asia',
                'flag_emoji' => '🇮🇷',
                'is_supported' => false, 'collections_enabled' => false, 'payouts_enabled' => false,
                'is_high_risk' => true, 'is_sanctioned' => true,
            ],
            [
                'iso2' => 'KP', 'iso3' => 'PRK', 'name' => 'North Korea',
                'official_name' => "Democratic People's Republic of Korea",
                'phone_code' => '850', 'default_currency' => 'KPW',
                'region' => 'Asia', 'subregion' => 'Eastern Asia',
                'flag_emoji' => '🇰🇵',
                'is_supported' => false, 'collections_enabled' => false, 'payouts_enabled' => false,
                'is_high_risk' => true, 'is_sanctioned' => true,
            ],
            [
                'iso2' => 'SY', 'iso3' => 'SYR', 'name' => 'Syria',
                'official_name' => 'Syrian Arab Republic',
                'phone_code' => '963', 'default_currency' => 'SYP',
                'region' => 'Asia', 'subregion' => 'Western Asia',
                'flag_emoji' => '🇸🇾',
                'is_supported' => false, 'collections_enabled' => false, 'payouts_enabled' => false,
                'is_high_risk' => true, 'is_sanctioned' => true,
            ],
            [
                'iso2' => 'CU', 'iso3' => 'CUB', 'name' => 'Cuba',
                'official_name' => 'Republic of Cuba',
                'phone_code' => '53', 'default_currency' => 'CUP',
                'region' => 'Americas', 'subregion' => 'Caribbean',
                'flag_emoji' => '🇨🇺',
                'is_supported' => false, 'collections_enabled' => false, 'payouts_enabled' => false,
                'is_high_risk' => true, 'is_sanctioned' => true,
            ],
            [
                'iso2' => 'RU', 'iso3' => 'RUS', 'name' => 'Russia',
                'official_name' => 'Russian Federation',
                'phone_code' => '7', 'default_currency' => 'RUB',
                'region' => 'Europe', 'subregion' => 'Eastern Europe',
                'flag_emoji' => '🇷🇺',
                'is_supported' => false, 'collections_enabled' => false, 'payouts_enabled' => false,
                'is_high_risk' => true, 'is_sanctioned' => true,
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['iso2' => $country['iso2']],
                $country
            );
        }

        $this->command->info('✓ Seeded ' . count($countries) . ' countries.');
    }
}